Repository googleapis/doc-templates, pull requests merged in 2021-03, with the labels that each got.

#144 cleanup: Update hanging test case
  tests/conftest.py
  tests/test_hanging.py
Labels: cla: yes, type: cleanup

#145 fix: mark managed ref content verbatim
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.html
  third_party/docfx/templates/devsite/partials/namespace.tmpl.partial
Labels: cla: yes

#150 ci: make UPDATE_GOLDENS only run golden tests
  ci/run_tests.sh
Labels: cla: yes

#151 feat: move Derived to its own section
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.AssetServiceClient.html
  third_party/docfx/templates/devsite/partials/class.header.tmpl.partial
  third_party/docfx/templates/devsite/token.json
Labels: cla: yes

#148 fix: improve alt link aside text
  testdata/goldens/go/index.html
  third_party/docfx/templates/devsite/partials/uref/namespace.tmpl.partial
Labels: automerge, cla: yes

#152 feat: make implements a comma separated list
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.AnalyzeIamPolicyRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.AnalyzeIamPolicyResponse.Types.IamPolicyAnalysis.Types.Stats.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.AnalyzeIamPolicyResponse.Types.IamPolicyAnalysis.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.AnalyzeIamPolicyResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.Asset.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.BatchGetAssetsHistoryRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.BatchGetAssetsHistoryResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.BigQueryDestination.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.CreateFeedRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.DeleteFeedRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ExportAssetsRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ExportAssetsResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ExportIamPolicyAnalysisRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ExportIamPolicyAnalysisResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.Feed.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.FeedName.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.FeedOutputConfig.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.GcsDestination.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.GcsOutputResult.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.GetFeedRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisOutputConfig.Types.BigQueryDestination.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisOutputConfig.Types.GcsDestination.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisOutputConfig.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisQuery.Types.AccessSelector.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisQuery.Types.IdentitySelector.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisQuery.Types.Options.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisQuery.Types.ResourceSelector.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisQuery.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.Types.Access.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.Types.AccessControlList.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.Types.Edge.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.Types.Identity.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.Types.IdentityList.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.Types.Resource.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisResult.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicyAnalysisState.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicySearchResult.Types.Explanation.Types.Permissions.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicySearchResult.Types.Explanation.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.IamPolicySearchResult.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ListFeedsRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ListFeedsResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.OutputConfig.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.OutputResult.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.PubsubDestination.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.Resource.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.ResourceSearchResult.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.SearchAllIamPoliciesRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.SearchAllIamPoliciesResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.SearchAllResourcesRequest.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.SearchAllResourcesResponse.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.TemporalAsset.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.TimeWindow.html
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.UpdateFeedRequest.html
  third_party/docfx/templates/devsite/ManagedReference.extension.js
  third_party/docfx/templates/devsite/partials/class.header.tmpl.partial
Labels: cla: yes

#153 feat: Rename "Derived" to "Derived Types"
  testdata/goldens/dotnet/Google.Cloud.Asset.V1.AssetServiceClient.html
  third_party/docfx/templates/devsite/token.json
Labels: automerge, cla: yes

#154 test: improve golden test failure messages
  tests/test_goldens.py
Labels: cla: yes

#158 fix: add space in alt link note
  testdata/goldens/go/index.html
  third_party/docfx/templates/devsite/partials/uref/namespace.tmpl.partial
Labels: cla: yes
