Repository googleapis/doc-templates, pull requests merged in 2021-01, with the labels that each got.

#100 tests: include .md files in docfx.json configs
  testdata/dotnet/docfx.json
  testdata/go/docfx.json
  testdata/nodejs/docfx.json
  testdata/python-small/docfx.json
Labels: cla: yes

#101 tests: update Go test package version
  testdata/go/go.mod
  testdata/go/go.sum
  testdata/go/obj/api/docs.metadata
  testdata/go/obj/api/index.yml
  testdata/go/obj/api/pkg-readme.md
  testdata/go/obj/api/toc.yml
  testdata/goldens/go/index.html
  testdata/goldens/go/pkg-readme.html
  testdata/goldens/go/toc.html
Labels: cla: yes

#102 feat: add alt link at top of pages
  testdata/go/obj/api/index.yml
  testdata/goldens/go/index.html
  third_party/docfx/templates/devsite/partials/uref/namespace.tmpl.partial
Labels: automerge, cla: yes

#103 feat: make hanging testcase optional
  README.md
  tests/conftest.py
  tests/test_hanging.py
Labels: cla: yes, type: feature request

#110 fix: make alt_link an <a> with class="external"
  testdata/goldens/go/index.html
  third_party/docfx/templates/devsite/partials/uref/namespace.tmpl.partial
Labels: cla: yes

#111 cleanup: change support from toc.html to toc.yaml
  testdata/goldens/dotnet/toc.yaml
  testdata/goldens/go/toc.yaml
  testdata/goldens/nodejs/toc.yaml
  testdata/goldens/python-small/toc.yaml
  tests/test_generate.py
  tests/test_hanging.py
  third_party/docfx/templates/devsite/README.md
  third_party/docfx/templates/devsite/toc.extension.js
  third_party/docfx/templates/devsite/toc.yaml.js
  third_party/docfx/templates/devsite/toc.yaml.tmpl
Labels: cla: yes, type: cleanup

#113 fix: remove html escape in toc.yaml
  testdata/goldens/dotnet/toc.yaml
  third_party/docfx/templates/devsite/partials/li.tmpl.partial
Labels: cla: yes

#116 fix!: only include the path for non-leaf TOC nodes
  testdata/goldens/dotnet/toc.yaml
  testdata/goldens/go/toc.yaml
  testdata/goldens/nodejs/toc.yaml
  testdata/goldens/python-small/toc.yaml
  third_party/docfx/templates/devsite/partials/li.tmpl.partial
Labels: cla: yes

#117 tests: update Go golden TOC input and output
  testdata/go/obj/api/toc.yml
  testdata/goldens/go/toc.yaml
Labels: cla: yes

#120 build: migrate to flakybot
  ci/trampoline_v2.sh
Labels: cla: yes
